### ISSUE TITLE
Problem with strapi v4.14.4, @localazy/strapi-plugin v0.2.2 and yarn

### ISSUE THREAD

**Issue by marcobaradel** [localazy/strapi-plugin#40]
Hi,
recently i decite to insert the localazy/strapi-plugin to my strapi project.

Actually I'm using strapi v4.14.4 with node v18.16.0 and yarn v3.6.4.
Using yarn add @localazy/strapi-plugin automatically insert v0.2.2 of the plugin (i think that's correct), but when i run yarn build or yarn develop the process crush with this error:

yarn develop
Building your admin UI with development configuration...

● Webpack █████████████████████████ building (44%) 0/1 entries 11661/11695 dependencies 3141/3421 modules 270 active
 esbuild-loader › .cache\admin\src\content-manager\pages\ListView\components\BulkActionButtons\ConfirmBulkActionDialog\index.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'zlib' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
        - install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "zlib": false }
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\Compilation.js:2022:28
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
resolve 'zlib' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'
  Parsed request is a module
  using description file: C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\MarcoBaradel\project\made_strapi\node_modules
        single file module
          using description file: C:\Users\MarcoBaradel\project\made_strapi\package.json (relative path: ./node_modules/zlib)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.tsx doesn't exist
        C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib doesn't exist
      C:\Users\MarcoBaradel\project\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'zlib' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
        - install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "zlib": false }
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\Compilation.js:2022:28
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
resolve 'zlib' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'
  Parsed request is a module
  using description file: C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\MarcoBaradel\project\made_strapi\node_modules
        single file module
          using description file: C:\Users\MarcoBaradel\project\made_strapi\package.json (relative path: ./node_modules/zlib)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib.tsx doesn't exist
        C:\Users\MarcoBaradel\project\made_strapi\node_modules\zlib doesn't exist
      C:\Users\MarcoBaradel\project\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory

--------------------------------------------------------------------------------------------------
I try to force in package.json the version 0.1.14 and all works good.
Someone know why about this error? I prefer to switch to the last version if is possible.

Thanks in advance.

**Comment by marcobaradel** [comment]
I did some test with plugin versions and i found that the plugin stop to work after this commit: 46aaeb036c3dcabefa9ec13483fc1f43c3745467.
There is maybe a substitute of this command: npx @localazy/strapi-plugin for yarn that not disable yarn and use npm? Or the problem is caused by something different?

**Comment by marcobaradel** [comment]
Hi,
i did all configuration steps correctly.
The problem presents when i run "yarn build" command, to build the admin.
The error appear only from version >0.1.18 of the plugin.
I confirm that the npx command works correctly.
Have any idea about this error? Still the same of the opening issue message (i re-write it below)
yarn build
Building your admin UI with development configuration...

● Webpack █████████████████████████ building (64%) 1/1 entries 11765/11896 dependencies 3170/3431 modules 222 active
 esbuild-loader › .cache\admin\src\pages\SettingsPage\pages\Webhooks\EditView\components\HeadersInput\Combobox.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'http' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\Compilation.js:2022:28
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
resolve 'http' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'
  Parsed request is a module
  using description file: C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\MarcoBaradel\project\made_strapi\node_modules
        single file module
          using description file: C:\Users\MarcoBaradel\project\made_strapi\package.json (relative path: ./node_modules/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.tsx doesn't exist
        C:\Users\MarcoBaradel\project\made_strapi\node_modules\http doesn't exist
      C:\Users\MarcoBaradel\project\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'http' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\Compilation.js:2022:28
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:817:13
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (C:\Users\MarcoBaradel\project\made_strapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:448:22
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:118:11
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:689:25
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:893:8
    at C:\Users\MarcoBaradel\project\made_strapi\node_modules\webpack\lib\NormalModuleFactory.js:1013:5
resolve 'http' in 'C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist'
  Parsed request is a module
  using description file: C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\dist\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\socket.io\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\project\made_strapi\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\MarcoBaradel\project\made_strapi\node_modules
        single file module
          using description file: C:\Users\MarcoBaradel\project\made_strapi\package.json (relative path: ./node_modules/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\MarcoBaradel\project\made_strapi\node_modules\http.tsx doesn't exist
        C:\Users\MarcoBaradel\project\made_strapi\node_modules\http doesn't exist
      C:\Users\MarcoBaradel\project\node_modules doesn't exist or is not a directory
      C:\Users\MarcoBaradel\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory

**Comment by david-vaclavek** [comment]
Hello, sorry for the late reply, I was out of the office.

I'm not able to reproduce the issue using the steps you mentioned.
Everything works correctly on my side.

Steps:
1. Run `yarn add @localazy/strapi-plugin && npx @localazy/strapi-plugin`
2. Create `webpack.config.js` file (or update it) with the contents in the newly created `webpack.config.localazy-strapi-plugin.example.js` file
3. Run `yarn build` (or run directly step 4)
4. Run `yarn develop`
5. The Strapi instance runs without any problems.

If you're not still able to make it work, send me a screencast video of the process. I'll take a deeper look then.

Closing: Cannot reproduce.
